### ISSUE TITLE
Where can I see ADL dataset annotated 21 classes?

### ISSUE THREAD

**Issue by kazucmpt** [sagarverma/ego_action_recognition#1]
Thank you for your providing source code of the paper.
It helps us a lot!!

I have a question about your experiment.
According to your paper, you evaluated your method on ADL and you wrote the class number of ADL is 21. I downloaded ADL dataset from [this page](https://www.csee.umbc.edu/~hpirsiav/papers/ADLdataset/) and I found the number of classes are 32.

I want to see ground truth labels of ADL dataset annotated 21 class. Where can I see it?

Best,

**Comment by sagarverma** [comment]
Thanks for the question. We have used [this](http://cvit.iiit.ac.in/projects/FirstPersonActions/) version of ADL split to make it comparable with [this](http://suriyasingh.github.io/EgoConvNetCVPR2016.pdf) work.

**Comment by kazucmpt** [comment]
Thank you very much for your quick reply. 

[This version](http://cvit.iiit.ac.in/projects/FirstPersonActions/) of ADL dataset has only 20 classes.

"take"  "wash"  "pour"   "open"   "put"  "brush"  "close"  "wipe"  "stir"  "type" 
"dip"  "write"  "wear" "spray" "flip" "swtichon" "tear" "comb" "scoop" "bg"

But you wrote that ADL dataset has 21 classes in your paper. Is it a typo?

**Comment by sagarverma** [comment]
It is a typo. Thanks for pointing it out, I will update the table. Results are for the above mentioned 20 classes.

**Comment by kazucmpt** [comment]
Thank you.
